apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: admin-token
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: network_metrics
      tlsSkipVerify: true
    editable: true